### ISSUE TITLE
Advanced tab in settings doesn't show anything

### ISSUE THREAD

**Issue by cp2004** [OctoPrint/OctoPrint-FirmwareUpdater#232] opened 2021-03-27 15:20 UTC
https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/0b93248d1b4642ee1443cf6fa961b7b662f1d5e7/octoprint_firmwareupdater/templates/firmwareupdater_settings.jinja2#L104

It looks like there is no `#advanced` anywhere as one of the tabs.

![image](https://user-images.githubusercontent.com/31997505/112725378-d07bfc80-8f0f-11eb-8922-7cbcab4ebc4f.png)
![image](https://user-images.githubusercontent.com/31997505/112725383-d83ba100-8f0f-11eb-85ca-488678c83c2a.png)

Any more questions let me know 😄

**Comment by benlye** [comment] 2021-03-27 15:44
Can't reproduce that here...
![image](https://user-images.githubusercontent.com/23322579/112725965-d4f5e480-8f12-11eb-9c7a-904bafe8120c.png)

Advanced tab is defined on line 275:
https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/master/octoprint_firmwareupdater/templates/firmwareupdater_settings.jinja2#L275

Do the other tabs work?

I wonder if there is some other element in the UI on your system with the id 'advanced' and maybe I need to use more unique identifiers?  Do you have other plugins enabled that might be causing a problem?  Can you try disabling them?

**Comment by cp2004** [comment] 2021-03-27 15:48
I have a decent number of plugins installed - not sure how I didn't find the definition of advanced tab before. I searched, promise...

For my plugins, if I remember I try and prefix the IDs I use if they are common. Something like `#FWU-advanced`?

Just checked in the devtools, it appears to be the spaghetti detective that also has an 'advanced' ID - at least, that's *one* of them, the one jquery is picking up.

**Comment by benlye** [comment] 2021-03-27 15:54
I should have seen that coming.  I use unique IDs on the modals but forgot to do it when I implemented the settings tabs.

I'll do a dev version later on today with unique IDs for those elements.  If you could test it and confirm it fixes this I'll do a stable release.

**Comment by cp2004** [comment] 2021-03-27 16:00
Thank you 😄 
I also asked TSD if they would do the same, to reduce the likelihood of things like this happening again. Advanced is a fairly common tab name.

**Comment by benlye** [comment] 2021-03-27 17:18
Should be fixed in v1.10.10b3 in the development release channel.

**Comment by cp2004** [comment] 2021-03-27 17:37
Tested, works great 😄 
Shame I can't be this fast in plugin development...

**Comment by benlye** [comment] 2021-03-27 19:03
Fixed in v1.10.10.

**Closed by benlye** 2021-03-27 19:03 UTC
Labels: bug
