### ISSUE TITLE
Firmware updater PI has problems with SKR1.4 using usbmount

### ISSUE THREAD

**Issue by TxBillbr** [OctoPrint/OctoPrint-FirmwareUpdater#138] opened 2020-05-30 19:46 UTC
**Hardware Setup**
Octoprint 1.40 -> SKR 1.4 Turbo
Uname: Linux octopi 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux
**Describe the problem**
Attempted to setup firmware updater per the instructions on the plugin github. usbmount did not seem to mount the usb micro sd.

___
**Log Files**
dmesg snip with relevant lines

[    1.619293] usb 1-1.4: New USB device found, idVendor=1d50, idProduct=6029, bcdDevice= 1.00
[    1.619328] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    1.619359] usb 1-1.4: Product: Marlin USB Device
[    1.619383] usb 1-1.4: Manufacturer: marlinfw.org
[    1.619408] usb 1-1.4: SerialNumber: 0D00201CAF37A0805BBFB7B4F50020C3
[    1.619649] systemd[1]: Detected architecture arm.
[    1.628490] usb-storage 1-1.4:1.2: USB Mass Storage device detected
[    1.629159] scsi host0: usb-storage 1-1.4:1.2
[    1.629724] systemd[1]: Set hostname to <octopi>.
[    1.636809] systemd[1]: Failed to bump fs.file-max, ignoring: Invalid argument
[    1.931871] systemd[1]: File /lib/systemd/system/systemd-journald.service:12 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
[    1.931933] systemd[1]: Proceeding WITHOUT firewalling in effect! (This warning is only shown for the first loaded unit using IP firewalling.)
[    1.966844] systemd[1]: /etc/systemd/system/systemd-udevd.service.d/override.conf:3: Unknown lvalue 'Mountflags' in section 'Service', ignoring
[    2.274485] systemd[1]: Listening on udev Control Socket.
[    2.275546] systemd[1]: Listening on initctl Compatibility Named Pipe.
[    2.276776] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
[    2.643644] scsi 0:0:0:0: Direct-Access     Marlin   SDCard 01        1.0  PQ: 0 ANSI: 0 CCS
[    2.696548] sd 0:0:0:0: [sda] Attached SCSI removable disk

___
Octoprint snip when using /tmp as flash location - **tells me plugin is working as expected**.

2020-05-29 20:33:51,259 - octoprint.startup - INFO - ******************************************************************************
2020-05-29 20:33:51,260 - octoprint.startup - INFO - Starting OctoPrint 1.4.0
2020-05-29 20:33:51,261 - octoprint.startup - INFO - ******************************************************************************
2020-05-29 20:33:51,575 - octoprint.util.connectivity_checker - INFO - Connectivity changed from offline to online
2020-05-29 20:33:51,577 - octoprint.startup - INFO - Blacklist processing done, adding 1 blacklisted plugin versions: roomtemp (any)
2020-05-29 20:33:51,606 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2020-05-29 20:33:52,242 - octoprint.plugin.core - INFO - Found 16 plugin(s) providing 16 mixin implementations, 29 hook handlers
2020-05-29 20:33:52,341 - octoprint.server.heartbeat - INFO - Starting server heartbeat, 900.0s interval
2020-05-29 20:33:52,355 - octoprint.server - INFO - Intermediary server started
2020-05-29 20:33:52,355 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2020-05-29 20:33:52,418 - octoprint.plugin.core - INFO - Found 16 plugin(s) providing 16 mixin implementations, 29 hook handlers
2020-05-29 20:33:52,435 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/pi/.octoprint/uploads...
2020-05-29 20:33:52,436 - octoprint.filemanager.storage - INFO - ... file metadata for /home/pi/.octoprint/uploads initialized successfully.
2020-05-29 20:33:52,439 - octoprint.server - INFO - Added new permission from plugin action_command_prompt: PLUGIN_ACTION_COMMAND_PROMPT_INTERACT (needs: u"Need(method='role', value=u'plugin_action_command_prompt_interact')")
2020-05-29 20:33:52,440 - octoprint.server - INFO - Added new permission from plugin announcements: PLUGIN_ANNOUNCEMENTS_READ (needs: u"Need(method='role', value=u'plugin_announcements_read')")
2020-05-29 20:33:52,440 - octoprint.server - INFO - Added new permission from plugin announcements: PLUGIN_ANNOUNCEMENTS_MANAGE (needs: u"Need(method='role', value=u'plugin_announcements_manage'), Need(method='role', value=u'plug
in_announcements_read')")
2020-05-29 20:33:52,441 - octoprint.server - INFO - Added new permission from plugin appkeys: PLUGIN_APPKEYS_ADMIN (needs: u"Need(method='role', value=u'plugin_appkeys_admin')")
2020-05-29 20:33:52,442 - octoprint.server - INFO - Added new permission from plugin backup: PLUGIN_BACKUP_ACCESS (needs: u"Need(method='role', value=u'plugin_backup_access')")
2020-05-29 20:33:52,443 - octoprint.server - INFO - Added new permission from plugin logging: PLUGIN_LOGGING_MANAGE (needs: u"Need(method='role', value=u'plugin_logging_manage')")
2020-05-29 20:33:52,444 - octoprint.server - INFO - Added new permission from plugin pi_support: PLUGIN_PI_SUPPORT_STATUS (needs: u"Need(method='role', value=u'plugin_pi_support_check')")
2020-05-29 20:33:52,444 - octoprint.server - INFO - Added new permission from plugin pluginmanager: PLUGIN_PLUGINMANAGER_MANAGE (needs: u"Need(method='role', value=u'plugin_pluginmanager_manage')")
2020-05-29 20:33:52,446 - octoprint.server - INFO - Added new permission from plugin pluginmanager: PLUGIN_PLUGINMANAGER_INSTALL (needs: u"Need(method='role', value=u'plugin_pluginmanager_install'), Need(method='role', value=u'pl
ugin_pluginmanager_manage')")
2020-05-29 20:33:52,446 - octoprint.server - INFO - Added new permission from plugin printer_safety_check: PLUGIN_PRINTER_SAFETY_CHECK_DISPLAY (needs: u"Need(method='role', value=u'plugin_printer_safety_check_display')")
2020-05-29 20:33:52,447 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_CHECK (needs: u"Need(method='role', value=u'plugin_softwareupdate_check')")
2020-05-29 20:33:52,448 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_UPDATE (needs: u"Need(method='role', value=u'plugin_softwareupdate_update')")
2020-05-29 20:33:52,457 - octoprint.access.users - INFO - Migrating user billbr to new granular permission system
2020-05-29 20:33:52,484 - octoprint.plugins.softwareupdate - INFO - Version cache was created for another version of OctoPrint, not using it
2020-05-29 20:33:53,036 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python2 -m pip" as command to invoke pip
2020-05-29 20:33:53,587 - octoprint.util.pip - INFO - Version of pip is 19.3.1
2020-05-29 20:33:53,588 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python2.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2020-05-29 20:33:53,589 - octoprint.util.pip - INFO - ==> pip ok -> yes
2020-05-29 20:33:53,592 - octoprint.plugin.core - INFO - Initialized 16 plugin implementation(s)
2020-05-29 20:33:53,644 - octoprint.plugin.core - INFO - 16 plugin(s) registered with the system:
|  Action Command Prompt Support (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/action_command_prompt
|  Announcement Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/announcements
|  Anonymous Usage Tracking (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/tracking
|  Application Keys Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/appkeys
|  Backup & Restore (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/backup
|  Core Wizard (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/corewizard
|  Discovery (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/discovery
|  Error Tracking (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/errortracking
|  Firmware Updater (1.7.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_firmwareupdater
|  Logging (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/logging
|  Login UI (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/loginui
|  Pi Support Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/pi_support
|  Plugin Manager (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  Printer Safety Check (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/printer_safety_check
|  Software Update (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  Virtual Printer (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
Prefix legend: ! = disabled, # = blacklisted, * = incompatible
2020-05-29 20:33:53,653 - octoprint.environment - INFO - Detected environment is Python 2.7.16 under Linux (linux2). Details:
|  hardware:
|      cores: 4
|      freq: 1500.0
|      ram: 4041732096
|  os:
|      id: linux
|      platform: linux2
|  plugins:
|      pi_support:
|          model: Raspberry Pi 4 Model B Rev 1.1
|          octopi_version: 0.17.0
|  python:
|      pip: 19.3.1
|      version: 2.7.16
|      virtualenv: /home/pi/oprint
2020-05-29 20:33:53,660 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/webassets...
2020-05-29 20:33:53,674 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/.webassets-cache...
2020-05-29 20:33:54,127 - octoprint.server - INFO - Shutting down intermediary server...
2020-05-29 20:33:54,286 - octoprint.server - INFO - Intermediary server shut down
2020-05-29 20:33:54,287 - octoprint.events - INFO - Processing startup event, this is our first event
2020-05-29 20:33:54,289 - octoprint.events - INFO - Adding 1 events to queue that were held back before startup event
2020-05-29 20:33:54,293 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2020-05-29 20:33:54,315 - octoprint.server.util.watchdog - INFO - Running initial scan on watched folder...
2020-05-29 20:33:54,329 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2020-05-29 20:33:54,339 - octoprint.server.util.watchdog - INFO - ... initial scan done.
2020-05-29 20:33:54,476 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2020-05-29 20:33:54,590 - octoprint.plugins.discovery - INFO - Registered 'OctoPrint instance on octopi' for _http._tcp
2020-05-29 20:33:54,825 - octoprint.plugins.discovery - INFO - Registered 'OctoPrint instance on octopi' for _octoprint._tcp
2020-05-29 20:33:55,007 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on octopi for SSDP
2020-05-29 20:33:55,236 - octoprint.server - INFO - Listening on http://127.0.0.1:5000
2020-05-29 20:33:55,443 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2020-05-29 20:33:55,929 - octoprint.plugins.pluginmanager - INFO - Loaded notice data from disk, was still valid
2020-05-29 20:33:56,094 - octoprint.server.util.sockjs - INFO - New connection from client: ::ffff:192.168.1.114
2020-05-29 20:33:56,356 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python2 -m pip" as command to invoke pip
2020-05-29 20:33:56,357 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python2 -m pip" as command to invoke pip
2020-05-29 20:33:56,374 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python2.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2020-05-29 20:33:56,377 - octoprint.util.pip - INFO - ==> pip ok -> yes
2020-05-29 20:33:56,434 - octoprint.plugins.pluginmanager - INFO - Loaded notice data from disk, was still valid
2020-05-29 20:33:56,457 - octoprint.server.util.flask - INFO - Passively logging in user billbr from ::ffff:192.168.1.114
2020-05-29 20:33:56,458 - octoprint.access.users - INFO - Logged in user: billbr
2020-05-29 20:33:56,473 - octoprint.server.util.sockjs - INFO - User billbr logged in on the socket from client ::ffff:192.168.1.114
2020-05-29 20:33:56,600 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python2 -m pip" as command to invoke pip
2020-05-29 20:33:58,158 - octoprint.server.util.flask - INFO - Passively logging in user billbr from ::ffff:192.168.1.114
2020-05-29 20:33:58,158 - octoprint.access.users - INFO - Logged in user: billbr
2020-05-29 20:33:58,603 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python2.7/site-packages/ (writable -> yes), --user flag needed -> no, virtual env -> yes
2020-05-29 20:33:58,604 - octoprint.util.pip - INFO - ==> pip ok -> yes
2020-05-29 20:33:58,622 - octoprint.plugins.softwareupdate - INFO - Saved version cache to disk
2020-05-29 20:33:58,700 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://192.168.1.204/'}
2020-05-29 20:33:59,424 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {'octoprint_uptime': 6}
2020-05-29 20:34:00,538 - octoprint.plugins.tracking - INFO - Sent tracking event pong, payload: {'plugins': u'firmwareupdater:1.7.0'}
2020-05-29 20:34:01,519 - octoprint.plugins.tracking - INFO - Sent tracking event startup, payload: {'python': '2.7.16', 'ram': 4041732096L, u'octopi_version': u'0.17.0', 'version': u'1.4.0', 'pip': '19.3.1', 'cores': 4, 'freq':
1500.0, u'pi_model': u'Raspberry Pi 4 Model B Rev 1.1', 'os': 'linux'}
2020-05-29 20:34:05,772 - octoprint.server.preemptive_cache - INFO - ... done in 7.07s
2020-05-29 20:34:05,779 - octoprint.server.util.sockjs - INFO - Client connection closed: ::ffff:192.168.1.114
2020-05-29 20:34:06,297 - octoprint.server.util.sockjs - INFO - New connection from client: ::ffff:192.168.1.114
2020-05-29 20:34:06,358 - octoprint.server.util.flask - INFO - Passively logging in user billbr from ::ffff:192.168.1.114
2020-05-29 20:34:06,358 - octoprint.access.users - INFO - Logged in user: billbr
2020-05-29 20:34:07,663 - octoprint.server.util.sockjs - INFO - User billbr logged in on the socket from client ::ffff:192.168.1.114
2020-05-29 20:35:17,944 - octoprint.util.comm - INFO - Changing monitoring state from "Offline" to "Detecting serial port"
2020-05-29 20:35:18,057 - octoprint.util.comm - INFO - Changing monitoring state from "Detecting serial port" to "Opening serial port"
2020-05-29 20:35:18,077 - octoprint.util.comm - INFO - Changing monitoring state from "Opening serial port" to "Detecting baudrate"
2020-05-29 20:35:19,111 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2020-05-29 20:35:19,118 - octoprint.util.comm - INFO - Changing monitoring state from "Detecting baudrate" to "Operational"
2020-05-29 20:35:19,126 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2020-05-29 20:35:19,136 - octoprint.plugins.firmwareupdater - INFO - Got CONNECTED event
2020-05-29 20:35:19,138 - octoprint.plugins.firmwareupdater - INFO - Run postflash flag is not set
2020-05-29 20:35:19,145 - octoprint.util.comm - INFO - Printer reports firmware name "Marlin 2.0.5.3 (GitHub)"
2020-05-29 20:35:19,181 - octoprint.util.comm - INFO - Firmware states that it supports temperature autoreporting
2020-05-29 20:35:19,950 - octoprint.plugins.tracking - INFO - Sent tracking event printer_connected, payload: {u'printer_baudrate': 0, u'printer_port': u'AUTO', 'firmware_name': u'Marlin 2.0.5.3 (GitHub)'}
2020-05-29 20:39:51,638 - octoprint.plugins.firmwareupdater - INFO - Firmware update started
2020-05-29 20:39:51,645 - octoprint.plugins.firmwareupdater - INFO - Disconnecting from printer
2020-05-29 20:39:51,664 - octoprint.util.comm - INFO - Changing monitoring state from "Operational" to "Offline"
2020-05-29 20:39:51,679 - octoprint.plugins.firmwareupdater - INFO - Unmounting SD card: 'sudo umount /tmp'
2020-05-29 20:39:51,771 - octoprint.plugins.firmwareupdater - INFO - Pre-flash reset: attempting to reset the board
2020-05-29 20:39:51,774 - octoprint.plugins.firmwareupdater - INFO - Resetting LPC1768 at '/dev/ttyACM0'
2020-05-29 20:39:51,851 - octoprint.plugins.firmwareupdater - INFO - Waiting for LPC1768 at '/dev/ttyACM0' to reset
2020-05-29 20:39:52,506 - octoprint.plugins.firmwareupdater - INFO - LPC1768 at '/dev/ttyACM0' is resetting
2020-05-29 20:39:55,743 - octoprint.plugins.firmwareupdater - INFO - LPC1768 at '/dev/ttyACM0' reset in 3.88 seconds
2020-05-29 20:40:05,398 - octoprint.plugins.firmwareupdater - INFO - Flashing successful.
2020-05-29 20:40:05,406 - octoprint.plugins.firmwareupdater - INFO - No postflash gcode or postflash is disabled, setting run_postflash_gcode to false
2020-05-29 20:40:05,412 - octoprint.plugins.firmwareupdater - INFO - Reconnecting to printer: port=/dev/ttyACM0, baudrate=115200, profile={'heatedChamber': False, 'name': 'Tazmania', 'color': 'default', 'axes': {'y': {'speed': 60
00, 'inverted': False}, 'x': {'speed': 6000, 'inverted': False}, 'z': {'speed': 200, 'inverted': False}, 'e': {'speed': 300, 'inverted': False}}, 'heatedBed': True, 'volume': {'origin': 'lowerleft', 'formFactor': 'rectangular', '
depth': 200.0, 'width': 200.0, 'custom_box': False, 'height': 200.0}, 'model': 'TAZ5.3', 'id': '_default', 'extruder': {'count': 1, 'nozzleDiameter': 0.4, 'offsets': [(0.0, 0.0)], 'sharedNozzle': False}}
2020-05-29 20:40:05,516 - octoprint.util.comm - INFO - Changing monitoring state from "Offline" to "Opening serial port"
2020-05-29 20:40:05,522 - octoprint.util.comm - INFO - Changing monitoring state from "Opening serial port" to "Connecting"
2020-05-29 20:40:05,535 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2020-05-29 20:40:11,889 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2020-05-29 20:40:11,894 - octoprint.util.comm - INFO - Changing monitoring state from "Connecting" to "Operational"
2020-05-29 20:40:11,917 - octoprint.plugins.firmwareupdater - INFO - Got CONNECTED event
2020-05-29 20:40:11,919 - octoprint.plugins.firmwareupdater - INFO - Run postflash flag is not set
2020-05-29 20:40:11,924 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2020-05-29 20:40:11,932 - octoprint.util.comm - INFO - Printer reports firmware name "Marlin 2.0.5.3 (GitHub)"
2020-05-29 20:40:11,981 - octoprint.util.comm - INFO - Firmware states that it supports temperature autoreporting
2020-05-29 20:40:12,659 - octoprint.plugins.tracking - INFO - Sent tracking event printer_connected, payload: {u'printer_baudrate': 115200, u'printer_port': '/dev/ttyACM0', 'firmware_name': u'Marlin 2.0.5.3 (GitHub)'}
2020-05-29 20:45:47,605 - octoprint.util.comm - INFO - Changing monitoring state from "Operational" to "Offline"
2020-05-29 20:46:35,893 - octoprint.util.comm - INFO - Changing monitoring state from "Offline" to "Opening serial port"
2020-05-29 20:46:35,895 - octoprint.util.comm - INFO - Changing monitoring state from "Opening serial port" to "Connecting"
2020-05-29 20:46:35,901 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2020-05-29 20:46:35,903 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2020-05-29 20:46:35,906 - octoprint.util.comm - INFO - Changing monitoring state from "Connecting" to "Operational"
2020-05-29 20:46:35,911 - octoprint.plugins.firmwareupdater - INFO - Got CONNECTED event
2020-05-29 20:46:35,912 - octoprint.plugins.firmwareupdater - INFO - Run postflash flag is not set
2020-05-29 20:46:35,914 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2020-05-29 20:46:35,919 - octoprint.util.comm - INFO - Printer reports firmware name "Marlin 2.0.5.3 (GitHub)"
2020-05-29 20:46:35,931 - octoprint.util.comm - INFO - Firmware states that it supports temperature autoreporting

**Additional context**
Device shows up in /dev/disk/by-id as usb-Marlin_SDCard_01_0D00201CAF37A0805BBFB7B4F50020C3-0:0

lsusb sees the marlin board
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 1d50:6029 OpenMoko, Inc.
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

---
**udevadm test --action=add /sys/block/sda**

This program is for debugging only, it does not run any program
specified by a RUN key. It may show incorrect results, because
some values may be different, or not available at a simulation run.

Load module index
Skipping empty file: /etc/systemd/network/99-default.link
Created link configuration context.
Reading rules file: /lib/udev/rules.d/10-local-rpi.rules
Reading rules file: /lib/udev/rules.d/15-i2c-modprobe.rules
Reading rules file: /lib/udev/rules.d/40-usb_modeswitch.rules
Reading rules file: /lib/udev/rules.d/50-firmware.rules
Reading rules file: /lib/udev/rules.d/50-udev-default.rules
Reading rules file: /lib/udev/rules.d/55-dm.rules
Reading rules file: /lib/udev/rules.d/60-block.rules
Reading rules file: /lib/udev/rules.d/60-cdrom_id.rules
Reading rules file: /lib/udev/rules.d/60-crda.rules
Reading rules file: /lib/udev/rules.d/60-drm.rules
Reading rules file: /lib/udev/rules.d/60-evdev.rules
Reading rules file: /lib/udev/rules.d/60-flashrom.rules
Reading rules file: /lib/udev/rules.d/60-input-id.rules
Reading rules file: /lib/udev/rules.d/60-persistent-alsa.rules
Reading rules file: /lib/udev/rules.d/60-persistent-input.rules
Reading rules file: /lib/udev/rules.d/60-persistent-storage-dm.rules
Reading rules file: /lib/udev/rules.d/60-persistent-storage-tape.rules
Reading rules file: /lib/udev/rules.d/60-persistent-storage.rules
Reading rules file: /lib/udev/rules.d/60-persistent-v4l.rules
Reading rules file: /lib/udev/rules.d/60-sensor.rules
Reading rules file: /lib/udev/rules.d/60-serial.rules
Reading rules file: /lib/udev/rules.d/60-triggerhappy.rules
Reading rules file: /lib/udev/rules.d/64-btrfs.rules
Reading rules file: /lib/udev/rules.d/69-libmtp.rules
Reading rules file: /lib/udev/rules.d/70-joystick.rules
Reading rules file: /lib/udev/rules.d/70-microbit.rules
Reading rules file: /lib/udev/rules.d/70-mouse.rules
Reading rules file: /lib/udev/rules.d/70-power-switch.rules
Reading rules file: /lib/udev/rules.d/70-touchpad.rules
Reading rules file: /lib/udev/rules.d/70-uaccess.rules
Reading rules file: /lib/udev/rules.d/71-seat.rules
Reading rules file: /lib/udev/rules.d/73-seat-late.rules
Reading rules file: /lib/udev/rules.d/73-special-net-names.rules
Reading rules file: /lib/udev/rules.d/73-usb-net-by-mac.rules
Reading rules file: /lib/udev/rules.d/75-net-description.rules
Reading rules file: /lib/udev/rules.d/75-probe_mtd.rules
Reading rules file: /lib/udev/rules.d/78-sound-card.rules
Reading rules file: /lib/udev/rules.d/80-debian-compat.rules
Reading rules file: /lib/udev/rules.d/80-drivers.rules
Reading rules file: /lib/udev/rules.d/80-ifupdown.rules
Reading rules file: /lib/udev/rules.d/80-net-setup-link.rules
Reading rules file: /lib/udev/rules.d/80-noobs.rules
Reading rules file: /lib/udev/rules.d/85-hwclock.rules
Reading rules file: /lib/udev/rules.d/85-regulatory.rules
Reading rules file: /lib/udev/rules.d/89-alsa-ucm.rules
Reading rules file: /lib/udev/rules.d/90-alsa-restore.rules
Reading rules file: /lib/udev/rules.d/90-console-setup.rules
Reading rules file: /lib/udev/rules.d/90-pi-bluetooth.rules
Reading rules file: /etc/udev/rules.d/95-ads7846.rules
Reading rules file: /lib/udev/rules.d/95-dm-notify.rules
Reading rules file: /lib/udev/rules.d/97-hid2hci.rules
Reading rules file: /etc/udev/rules.d/99-com.rules
Reading rules file: /lib/udev/rules.d/99-systemd.rules
Reading rules file: /lib/udev/rules.d/usbmount.rules
Rules contain 196608 bytes tokens (16384 * 12 bytes), 23210 bytes strings
15373 strings (124791 bytes), 13054 de-duplicated (103901 bytes), 2320 trie nodes used
Invalid inotify descriptor.
DEVPATH=/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.4/1-1.4:1.2/host0/target0:0:0/0:0:0:0/block/sda
DEVNAME=/dev/sda
DEVTYPE=disk
MAJOR=8
MINOR=0
ACTION=add
SUBSYSTEM=block
ID_VENDOR=Marlin
ID_VENDOR_ENC=Marlin\x20\x20
ID_VENDOR_ID=1d50
ID_MODEL=SDCard_01
ID_MODEL_ENC=SDCard\x2001\x20\x20\x20\x20\x20\x20\x20
ID_MODEL_ID=6029
ID_REVISION=1.0
ID_SERIAL=Marlin_SDCard_01_0D00201CAF37A0805BBFB7B4F50020C3-0:0
ID_SERIAL_SHORT=0D00201CAF37A0805BBFB7B4F50020C3
ID_TYPE=disk
ID_INSTANCE=0:0
ID_BUS=usb
ID_USB_INTERFACES=:020200:0a0000:080650:
ID_USB_INTERFACE_NUM=02
ID_USB_DRIVER=usb-storage
DEVLINKS=/dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.4:1.2-scsi-0:0:0:0 /dev/disk/by-id/usb-Marlin_SDCard_01_0D00201CAF37A0805BBFB7B4F50020C3-0:0
ID_PATH=platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.4:1.2-scsi-0:0:0:0
ID_PATH_TAG=platform-fd500000_pcie-pci-0000_01_00_0-usb-0_1_4_1_2-scsi-0_0_0_0
TAGS=:systemd:
USEC_INITIALIZED=3492256
run: '/usr/share/usbmount/usbmount add'
Unload module index
Unloaded link configuration context.

running usbmount did not work.
Found this issue that indicates usbmount is  an orphan project.  https://raspberrypi.stackexchange.com/questions/100312/raspberry-4-usbmount-not-working

**Comment by CaptainSweatpants** [comment] 2020-09-21 04:41
This broke my serial connection to my printer from octoprint as well. Disabling it returned connection abilities to my SKR 1.4 turbo; I haven't found a solution yet to update firmware via Octoprint with this BTT SKR 1.4 T board. For now, the only way i can update Marlin is to enable usbmount, then plug it into windows and the firmware folder will open there. I drop firmware.bin and reboot the printer. then once updated, back to ssh'ing over to the RPi and disabling usbmount so octoprint can connect again. 

This isn't efficient at all.

**Comment by YHRen** [comment] 2020-10-03 19:49
Hi I have experienced the same problem after the update. SKR 1.4 T with Pi4 connected by GPIO pins. 

@CaptainSweatpants  can you `scp` the firmware ? I will give it a try after the current print is done.

**Comment by benlye** [comment] 2020-11-27 17:31
Duplicate of #149.  Closing this one because the other issue has more conversation.

**Closed by benlye** 2020-11-27 17:31 UTC
